apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: dev
  labels:
    version: v0.1.0
    messageQueue: rabbitmq
  name: rabbitmq-cluster
spec:
  serviceName: rabbitmq-service
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-data
      namespace: dev
      labels:
        version: v0.1.0
        messageQueue: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: hostpath
      resources:
        requests:
          storage: 300Mi
  replicas: 1
  selector:
    matchLabels:
      version: v0.1.0
      messageQueue: rabbitmq
  template:
    metadata:
      namespace: dev
      labels:
        version: v0.1.0
        messageQueue: rabbitmq
    spec:
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
      containers:
        - image: rabbitmq:3.11.3-alpine
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources:
            limits:
              cpu: 750m
              memory: 200Mi
            requests:
              cpu: 250m
              memory: 50Mi
          volumeMounts:
            - mountPath: /var/lib/rabbitmq/
              name: rabbitmq-data
            - mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
              name: rabbitmq-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: rabbitmq-service
  labels:
    version: v0.1.0
    messageQueue: rabbitmq
spec:
  clusterIP: None
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
  selector:
    version: v0.1.0
    messageQueue: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: rabbitmq-service-ui
  labels:
    version: v0.1.0
    messageQueue: rabbitmq
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 15672
      targetPort: 15672
  selector:
    statefulset.kubernetes.io/pod-name: rabbitmq-cluster-0
    version: v0.1.0
    messageQueue: rabbitmq
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: rabbitmq-config
    namespace: dev
data:
    enabled_plugins: |
      [rabbitmq_prometheus,rabbitmq_web_dispatch,rabbitmq_management_agent,rabbitmq_management].